# SPDX-License-Identifier: MIT-0
---
# defaults file for bootstrap

### Packages ###
packages:
  - ansible
  - python3-pip
  - python3-venv
  - git
  - curl
  - wget
  - unzip
  - jq

pip_packages:
  - ansible-lint

### Default SSH values ###
ssh_port: 22
ssh_user: "alex"
ssh_enable_password_authentication: true
ssh_enable_root_login: false
ssh_enable_pubkey_authentication: true

### Default Visudo values ###
visudo_user: "alex"
visudo_command: "ALL=(ALL) ALL" # L'utilisateur devra entrer son mot de passe pour sudo

### Default Users ###
users:
  - { name: "alex", groups: "sudo", shell: "/bin/bash", password: "password", ssh_key: "ssh-rsa AAAAB3NzaC1yc2EA" }
  - { name: "titi", groups: "sudo", shell: "/bin/bash", password: "toto-pwd", ssh_key: "ssh-rsa AMLKJIFMLKJS" }
  - { name: "toto", groups: "sudo", shell: "/bin/bash", password: "toto-pwd", ssh_key: "ssh-rsa AMLKJIFMLKJS" }
